add w21_An_overview_of_memory_management_in_Go English version
gocn/translator pull request #124
Opened 2021-05-22 09:48 UTC by haoheipi

2021-05-23 09:56 UTC, cvley requested changes

2021-05-23 09:56 UTC, cvley commented on 2021/w21_An_overview_of_memory_management_in_Go.md
> +随着程序的运行，对象被写入内存。在一些特定时刻当它们不再被需要时，它们应该被移除。这个过程被称为 **内存管理** 。本文旨在给出内存管理的概述，然后深入研究在 Go 中如何使用垃圾收集器实现内存管理。Go 的内存管理近些年已经发生了很大变化，未来很可能还会发生更多变化。如果您正在阅读这篇文章，并且您使用的是比 1.16 更高的 Go 版本，那么这里的一些信息可能已经过时了。
垃圾收集 => 垃圾回收

2021-05-23 09:56 UTC, cvley commented on 2021/w21_An_overview_of_memory_management_in_Go.md
> +[分代前提](https://www.memorymanagement.org/glossary/g.html#term-generational-hypothesis) 是假设寿命短的对象（如临时变量）最常被回收。因此，分代垃圾收集器主要关注最近分配的对象。然而如前所述，编译器优化允许 Go 编译器将具有已知生命周期的对象分配在栈上。[这意味着堆上的对象更少，因此垃圾收集的对象更少](http
分代前提 => 分代假设

2021-05-23 09:56 UTC, cvley commented on 2021/w21_An_overview_of_memory_management_in_Go.md
> +为什么像 Go 这样的语言提供了 **自动的动态内存管理** ，或者更简单地说，**垃圾收集**。具有垃圾收集功能的语言提供了如下好处:
为什么像 Go 这样的语言提供了 **自动的动态内存管理** ，或者更简单地说，**垃圾收集**
=> 
这是像 Go 这样的语言提供了 **自动的动态内存管理** ，或者更简单地说，**垃圾回收**的原因

2021-05-23 13:47 UTC, haoheipi commented on 2021/w21_An_overview_of_memory_management_in_Go.md
> +为什么像 Go 这样的语言提供了 **自动的动态内存管理** ，或者更简单地说，**垃圾收集**。具有垃圾收集功能的语言提供了如下好处:
done

2021-05-24 01:36 UTC, fivezh commented on 2021/w21_An_overview_of_memory_management_in_Go.md
> +[分代假设](https://www.memorymanagement.org/glossary/g.html#term-generational-hypothesis) 是寿命短的对象（如临时变量）最常被回收。因此，分代垃圾收集器主要关注最近分配的对象。然而如前所述，编译器优化允许 Go 编译器将具有已知生命周期的对象分配在栈上。[这意味着堆上的对象更少，因此垃圾收集的对象更少](https:
非代=>非分代

2021-05-24 01:36 UTC, fivezh commented on 2021/w21_An_overview_of_memory_management_in_Go.md
> +这是像 Go 这样的语言提供了 **自动的动态内存管理** ，或者更简单地说，**垃圾回收** 的原因。具有垃圾收集功能的语言提供了如下好处:
垃圾回收和垃圾收集，两个术语可以统一下

2021-05-24 02:44 UTC, haoheipi commented on 2021/w21_An_overview_of_memory_management_in_Go.md
> +这是像 Go 这样的语言提供了 **自动的动态内存管理** ，或者更简单地说，**垃圾回收** 的原因。具有垃圾收集功能的语言提供了如下好处:
统一成 "垃圾收集" 了

2021-05-25 01:22 UTC, merged