add 2022 w08 translation
gocn/translator pull request #215
Opened 2022-02-14 15:53 UTC by zxmfke

2022-02-20 13:17 UTC, fivezh requested changes

2022-02-20 13:17 UTC, fivezh commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +箭头表示channel的方向。在`chan`之前的箭头表明数据流是*进入*channel的，而`chan  `之后的箭头表明数据流是*流出*channel的。
这里原文的流入、流出应该是写反了

在`chan`之前的箭头表明数据流是*流出*channel的，而`chan`之后的箭头表明数据流是*流入*channel的

2022-02-20 13:17 UTC, fivezh commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +1. 哪个范围拥有channel？
scope 翻译成 作用域，比较合适

2022-02-20 13:17 UTC, fivezh commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +  - 与`WithCancel`的返回相同，但有一个背景期限，在指定的`time.Time`过后，将取消context。
但有一个背景期限
=》
但有一个后台运行期限

2022-02-21 00:53 UTC, zxmfke commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +1. 哪个范围拥有channel？
scope一直想着有个词，就一直想不出来，原来是作用域

2022-02-21 01:28 UTC, zxmfke commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +箭头表示channel的方向。在`chan`之前的箭头表明数据流是*进入*channel的，而`chan  `之后的箭头表明数据流是*流出*channel的。
这个我大致理解了，我再分析下，这边都有点歧义，感觉得分 <-chan 和 <-a

2022-02-21 14:21 UTC, zxmfke commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +3. go routine管理着共享资源的[所有权](#op)。(第17行)
这个没错，是连接到owner pattern

2022-02-21 14:21 UTC, zxmfke commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +Go的设计者们着重强调并发设计，将其作为一个方法论，其思想是重要信息之间是通过沟通[2](https://benjiv.com/go-native-concurrency-primitives/#fn:2)而不是阻塞和共享[3](https://benjiv.com/go-native-concurrency-primitives/#fn:3)。
fixed

2022-02-21 14:22 UTC, zxmfke commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +5. [`select`语句](#ss)用来校验是读还是写的请求。(第24和34行)
这个没错，是连接到owner pattern

2022-02-21 14:23 UTC, zxmfke commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
>  [*Back To Top*](#top)
这个原文中有，然后比较长，所以我就保留了

2022-02-21 14:29 UTC, zxmfke commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +在上面这个例子中，参数`ok`会是`false`，如果channel是关闭的。
中式英语，翻麻了最后

2022-02-22 12:06 UTC, zxmfke commented on 2022/w08_Go_Native_Concurrency_Primitives_&_Best_Practices.md
> +Go语言在创立之初就将并发定为第一公民。 Go语言是一种通过在语言中抽象出并发基本原理[1](https://benjiv.com/go-native-concurrency-primitives/#fn:1)背后的并行细节，使开发者能够轻松地编写高度并行程序的编程语言。
懂了

2022-02-22 12:29 UTC, merged